/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/scene.gltf --transform --typesnpm run start
Author: aaronjbryant (https://sketchfab.com/aaronjbryant)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arrow-curved-67d34a64164a43d4a07a2dc73e0db681
Title: Arrow Curved
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Material2.geometry} material={materials.Color_H04} position={[8.438, 12, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
